# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

gui:
  language: "en"
  nerdFontsVersion: "3"
  filterMode: fuzzy
  showNumstatInFilesView: true
  showDivergenceFromBaseBranch: arrowAndNumber
  showRandomTip: false
  theme:
    activeBorderColor:
      - "#A7C080"
      - bold
    inactiveBorderColor:
      - "#475258"
    searchingActiveBorderColor:
      - "#83C092"
      - bold
    optionsTextColor:
      - "#DBBC7F"
    selectedLineBgColor:
      - "#343F44"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#2D353B"
    cherryPickedCommitBgColor:
      - "#83C092"
    markedBaseCommitFgColor:
      - "#2D353B"
    markedBaseCommitBgColor:
      - "#DBBC7F"
    unstagedChangesColor:
      - "#E67E80"
    defaultFgColor:
      - "#D3C6AA"
