return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "stylua",
      "shfmt",
      -- "flake8",
      "prettier",
      "prettierd",
      "codelldb",
      "eslint-lsp",
      "json-lsp",
      "lua-language-server",
      "pyright",
      "ruff-lsp",
      "rust-analyzer",
      "taplo",
      "buf-language-server",
      "buf",
      "groovy-language-server",
      "hadolint",
      "js-debug-adapter",
    },
  },
}
