"$schema" = 'https://starship.rs/config-schema.json'

scan_timeout = 20
command_timeout = 500
palette = "everforest"
right_format = """
$memory_usage\
$status\
$cmd_duration\
$time
"""

[aws]
symbol = "  "

[buf]
symbol = " "

[bun]
symbol = " "

[c]
symbol = " "

[cpp]
symbol = " "

[cmake]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[deno]
symbol = " "

[directory]
read_only = " 󰌾"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[gcloud]
symbol = "  "

[git_branch]
symbol = " "

[git_commit]
tag_symbol = '  '
tag_disabled = false

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[jobs]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "
threshold = 70
format = 'via $symbol [${ram} (${ram_pct})( | ${swap})]($style) '
disabled = false

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[pixi]
symbol = "󰏗 "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[gradle]
symbol = " "

[cmd_duration]
min_time = 500
show_milliseconds = true
show_notifications = true

[git_status]
conflicted = "=$count"
ahead = "⇡$count"
behind = "⇣$count"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "?$count"
stashed = "\\$$count"
modified = "!$count"
staged = "+$count"
renamed = "»$count"
deleted = "✘$count"

[time]
use_12hr = false
disabled = false

[status]
map_symbol = true
disabled = false

[palettes.everforest]
bg_dim = "#232A2E"
bg0 = "#2D353B"
bg1 = "#343F44"
bg2 = "#3D484D"
bg3 = "#475258"
bg4 = "#4F585E"
bg5 = "#56635f"
bg_visual = "#543A48"
bg_red = "#514045"
bg_yellow = "#4D4C43"
bg_green = "#425047"
bg_blue = "#3A515D"
bg_purple = "#4A444E"
fg = "#D3C6AA"
red = "#E67E80"
orange = "#E69875"
yellow = "#DBBC7F"
green = "#A7C080"
aqua = "#83C092"
cyan = "#83C092"
blue = "#7FBBB3"
purple = "#D699B6"
grey0 = "#7A8478"
grey1 = "#859289"
grey2 = "#9DA9A0"
statusline1 = "#A7C080"
statusline2 = "#D3C6AA"
statusline3 = "#E67E80"
