# change prefix
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# enable mouse
set -g mouse on

# esc key no delay
set -s escape-time 0

# UTF-8 / 256Color
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# status line
set -g status-position bottom
set -g status-style "bg=#2D353B,fg=#D3C6AA"
set -g status-left "#[bold] #S #[default]"
set -g status-right "%Y-%m-%d %H:%M "

# window status
set -g window-status-current-style "bg=#3D484D,fg=#A7C080,bold"
set -g window-status-style "bg=#2D353B,fg=#859289"
set -g window-status-current-format "#[bold]#I:#W#F"
set -g window-status-format "#I:#W#F"

# pane
set -g pane-active-border-style "fg=#A7C080"
set -g pane-border-style "fg=#7A8478"

# vi mode
set -g mode-keys vi
set -g status-keys vi

# windows
set -g renumber-windows on
set -g remain-on-exit on

# history
set -g history-limit 50000

# reload config
bind R source-file ~/.tmux.conf \; display "Reloaded!"

# move pane keybindings
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R
