version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: '%(asctime)s | %(name)10s | %(levelname)8s | %(filename)s | %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: log/rolling.log
    maxBytes: 1048576
    backupCount: 20
    mode: a

loggers:
  dev:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  staging:
    level: INFO
    handlers: [console, file]
    propagate: no

  production:
    level: WARNING
    handlers: [file]
    propagate: no


root:
  level: DEBUG
  handlers: [console]