version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(filename)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: log/rolling.log
    maxBytes: 1048576
    backupCount: 20
    mode: a

loggers:
  development:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  staging:
    level: INFO
    handlers: [console, file]
    propagate: no

  production:
    level: WARNING
    handlers: [file]
    propagate: no


root:
  level: DEBUG
  handlers: [console]